In [1]:
import pandas as pd
import numpy as np
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [2]:
train.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0

In [3]:
train.isnull().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
train.dtypes

id                   int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard          float64
IsActiveMember     float64
EstimatedSalary    float64
Exited               int64
dtype: object

In [5]:
train.describe()

,id,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,165034.0000,1.650340e+05,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000,165034.000000
mean,82516.5000,1.569201e+07,656.454373,38.125888,5.020353,55478.086689,1.554455,0.753954,0.497770,112574.822734,0.211599
std,47641.3565,7.139782e+04,80.103340,8.867205,2.806159,62817.663278,0.547154,0.430707,0.499997,50292.865585,0.408443
min,0.0000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,41258.2500,1.563314e+07,597.000000,32.000000,3.000000,0.000000,1.000000,1.000000,0.000000,74637.570000,0.000000
50%,82516.5000,1.569017e+07,659.000000,37.000000,5.000000,0.000000,2.000000,1.000000,0.000000,117948.000000,0.000000
75%,123774.7500,1.575682e+07,710.000000,42.000000,7.000000,119939.517500,2.000000,1.000000,1.000000,155152.467500,0.000000
max,165033.0000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [6]:
test_ids=test["id"]

In [7]:
train.columns

Index(['id', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender',
       'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [8]:
train["Exited"].value_counts()

Exited
0    130113
1     34921
Name: count, dtype: int64

In [9]:
train["Exited"].value_counts(normalize=True)*100

Exited
0    78.840118
1    21.159882
Name: proportion, dtype: float64

In [10]:
train["Gender"].value_counts()

Gender
Male      93150
Female    71884
Name: count, dtype: int64

In [11]:
train["Geography"].value_counts()

Geography
France     94215
Spain      36213
Germany    34606
Name: count, dtype: int64

In [12]:
train["Surname"].nunique()

2797

In [13]:
train=train.drop(columns=["id","CustomerId","Surname"])
test=test.drop(columns=["id","CustomerId","Surname"])

In [14]:
train=pd.get_dummies(train,drop_first=True)
test=pd.get_dummies(test,drop_first=True)

In [15]:
train.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,668,33.0,3,0.00,2,1.0,0.0,181449.97,0,False,False,True
1,627,33.0,1,0.00,2,1.0,1.0,49503.50,0,False,False,True
2,678,40.0,10,0.00,2,1.0,0.0,184866.69,0,False,False,True
3,581,34.0,2,148882.54,1,1.0,1.0,84560.88,0,False,False,True
4,716,33.0,5,0.00,2,1.0,1.0,15068.83,0,False,True,True

In [16]:
X = train.drop("Exited", axis=1)
y = train["Exited"]

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,test_size=0.2,random_state=10)

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_valid_scaled=scaler.transform(X_valid)

In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000,random_state=10)
lr.fit(X_train_scaled,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

LogisticRegression(max_iter=1000, random_state=10)

In [20]:
y_pred=lr.predict(X_valid_scaled)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [21]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_valid,y_pred))

Accuracy: 0.8321265186172631

In [22]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

[[24749  1141]
 [ 4400  2717]]
              precision    recall  f1-score   support

           0       0.85      0.96      0.90     25890
           1       0.70      0.38      0.50      7117

    accuracy                           0.83     33007
   macro avg       0.78      0.67      0.70     33007
weighted avg       0.82      0.83      0.81     33007

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [24]:
knn_pred=knn.predict(X_valid_scaled)
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_valid,knn_pred))

Accuracy: 0.8464568121913534

In [25]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_valid, knn_pred))
print(classification_report(y_valid, knn_pred))

[[24104  1786]
 [ 3282  3835]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90     25890
           1       0.68      0.54      0.60      7117

    accuracy                           0.85     33007
   macro avg       0.78      0.73      0.75     33007
weighted avg       0.84      0.85      0.84     33007

In [26]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=10)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=10)

In [27]:
dt_pred=dt.predict(X_valid)
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_valid,dt_pred))

Accuracy: 0.7974369073226891

In [28]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_valid,dt_pred))
print(classification_report(y_valid,dt_pred))

[[22439  3451]
 [ 3235  3882]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87     25890
           1       0.53      0.55      0.54      7117

    accuracy                           0.80     33007
   macro avg       0.70      0.71      0.70     33007
weighted avg       0.80      0.80      0.80     33007

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=10)
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=10)

In [33]:
rf_pred=rf.predict(X_valid)
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_valid,rf_pred))

Accuracy: 0.8583936740691368

In [34]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_valid,rf_pred))
print(classification_report(y_valid,rf_pred))

[[24485  1405]
 [ 3269  3848]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     25890
           1       0.73      0.54      0.62      7117

    accuracy                           0.86     33007
   macro avg       0.81      0.74      0.77     33007
weighted avg       0.85      0.86      0.85     33007

In [36]:
from sklearn.model_selection import GridSearchCV
rf = RandomForestClassifier(random_state=10)

In [37]:
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20, None],
    "min_samples_split": [2, 5]
}

In [38]:
grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [39]:
grid.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=10), n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='accuracy')

In [40]:
print(grid.best_params_)
print(grid.best_score_)

{'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 100}
0.8643004823962604

In [44]:
best_rf = grid.best_estimator_

In [46]:
rf_tuned_pred = best_rf.predict(X_valid)

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_valid, rf_pred))
print(confusion_matrix(y_valid, rf_pred))
print(classification_report(y_valid, rf_pred))

Accuracy: 0.8583936740691368
[[24485  1405]
 [ 3269  3848]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91     25890
           1       0.73      0.54      0.62      7117

    accuracy                           0.86     33007
   macro avg       0.81      0.74      0.77     33007
weighted avg       0.85      0.86      0.85     33007

In [56]:
best_rf.fit(X, y)

RandomForestClassifier(max_depth=10, random_state=10)

In [59]:
test_pred = best_rf.predict(test)

In [60]:
submission = pd.DataFrame({
    "id": test_ids,
    "Exited": test_pred
})
submission.to_csv("submission.csv", index=False)